CC=g++
CFLAGS=-O3 -msse2 -c -DLINUX -I. -LSDL/lib -g
LDFLAGS=
SOURCES=flops_sse.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=flops_sse2

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(EXECUTABLE)
