CC=gcc
CPP=g++
CFLAGS=-O3 -mavx -D__AVX__ -I. -g
LDFLAGS=

SRC=gflops.cpp
OBJ=gflops.o
BIN=gflops




all: ${BIN}


${BIN}: ${OBJ}
	${CPP} $(CFLAGS) $(OBJ) -o $(BIN)   $(LDLIBS)

${OBJ}: ${SRC}
	${CPP} ${CFLAGS} -c ${SRC} -o ${OBJ}

clean:
	rm -f $(BIN) $(OBJ) gflops.exe



