.\" This man page is inspired in hello.1 from GNU hello-2.10.
.TH HITHERE "1" "December 2018" "hithere 1.0" "User Commands"
.SH NAME
hithere - greet user
.SH SYNOPSIS
.B hithere
.SH DESCRIPTION
greets the user, or the world.
.SH AUTHORS
Original work by Lars Wirzenius, 2010.
.br
Reverse engineered (with permission) by Alex Muntada, 2018.
