CC=g++
CFLAGS=-c -DLINUX -I. -LSDL/lib -g
LDFLAGS=-lSDL 
SOURCES=mbgroups_view.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=mbgroups_view

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS) 

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS) $(EXECUTABLE)
